# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(verbose_name='idd')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('last_points_count', models.IntegerField(default=0, verbose_name='last_points_count')),
                ('points_count', models.IntegerField(default=0, verbose_name='points_count')),
                ('need_update', models.BooleanField(default=False, verbose_name='need_update')),
            ],
        ),
        migrations.CreateModel(
            name='OzonPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(null=True, verbose_name='Id')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('deliveryType', models.CharField(max_length=250, verbose_name='deliveryType')),
                ('metro', models.CharField(max_length=250, verbose_name='metro')),
                ('area', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parserapp.AreaList')),
            ],
        ),
    ]
