# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(verbose_name='idd')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='OzonPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(null=True, verbose_name='Id')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('deliveryType', models.CharField(max_length=250, verbose_name='deliveryType')),
                ('metro', models.CharField(max_length=250, verbose_name='metro')),
            ],
        ),
    ]
