# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalvaPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250, verbose_name='uid')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('number', models.CharField(max_length=250, verbose_name='number')),
            ],
        ),
    ]
