# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_halvapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealist',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='visibility'),
        ),
        migrations.AddField(
            model_name='halvapoint',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='visibility'),
        ),
    ]
