# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0003_auto_20190730_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonpoints',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='visibility'),
        ),
    ]
