# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('stype', models.SmallIntegerField(choices=[(0, 'SERVICES'), (1, 'SENDER')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='sender',
            name='token',
            field=models.CharField(max_length=128, verbose_name='Токен'),
        ),
    ]
