# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signin', '0003_cameras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='url',
            field=models.CharField(max_length=256, verbose_name='URL камеры'),
        ),
    ]
