# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signin', '0004_auto_20180507_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='stype',
            field=models.SmallIntegerField(choices=[(1, '172.28.2.XX'), (0, '197.1.102.XX')], default=0, verbose_name='Тип'),
        ),
    ]
