# Generated by Django 2.0.5 on 2018-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, verbose_name='Клиентский номер')),
                ('barcodes', models.CharField(max_length=256, verbose_name='Баркод')),
                ('terminal', models.CharField(max_length=8, unique=True, verbose_name='Номер')),
                ('point_settlement', models.CharField(max_length=128, verbose_name='Населенный пункт')),
                ('point_address', models.TextField(verbose_name='Адрес')),
                ('consignor', models.CharField(default='', max_length=128, verbose_name='Отправитель')),
                ('date_added', models.DateTimeField(null=True, verbose_name='Дата создания')),
                ('delivery_date', models.DateTimeField(null=True, verbose_name='Дата доставки')),
                ('upload_date', models.DateTimeField(null=True, verbose_name='Дата выдачи')),
                ('status', models.SmallIntegerField(choices=[(2, 'В доставке'), (9, 'Возвращена'), (4, 'Выдана'), (10, 'Проблемная'), (11, 'Техническая проблема'), (6, 'Забрана на возврат'), (12, 'Отменена'), (3, 'Доставлена'), (7, 'На хранении'), (13, 'Хранение продлено клиентом'), (0, 'Создана'), (5, 'Просрочена'), (1, 'Ожидает приёмки'), (8, 'На возврате')], default=0, verbose_name='Статус')),
                ('cod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Наложенный платёж')),
                ('partner_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена услуг партнёра')),
                ('declared_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объявленная ценность')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('sender', models.CharField(max_length=128, verbose_name='Контрагент')),
            ],
            options={
                'db_table': 'Отчёт',
            },
        ),
    ]
