# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=8, verbose_name='Номер станции')),
                ('dt', models.DateTimeField(verbose_name='Дата и время проверки')),
                ('occupancy', models.IntegerField(verbose_name='Заполненность')),
            ],
            options={
                'verbose_name': 'Вместимость терминала',
                'verbose_name_plural': 'Вместимость терминалов',
                'db_table': 'ADM_capacity',
            },
        ),
    ]
