# Generated by Django 2.0.5 on 2018-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(8, 'На возврате'), (7, 'На хранении'), (6, 'Забрана на возврат'), (10, 'Проблемная'), (13, 'Хранение продлено клиентом'), (2, 'В доставке'), (9, 'Возвращена'), (12, 'Отменена'), (1, 'Ожидает приёмки'), (3, 'Доставлена'), (4, 'Выдана'), (5, 'Просрочена'), (11, 'Техническая проблема'), (0, 'Создана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
    ]
