# Generated by Django 2.0.5 on 2018-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180520_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(4, 'Выдана'), (6, 'Забрана на возврат'), (9, 'Возвращена'), (10, 'Проблемная'), (7, 'На хранении'), (13, 'Хранение продлено клиентом'), (8, 'На возврате'), (3, 'Доставлена'), (5, 'Просрочена'), (2, 'В доставке'), (0, 'Создана'), (1, 'Ожидает приёмки'), (11, 'Техническая проблема'), (12, 'Отменена')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
    ]
