# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='UID сообщения')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата модификации')),
                ('meta', models.CharField(blank=True, max_length=550, null=True, verbose_name='Дополнительные данные')),
                ('order_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Клиентский номер')),
                ('barcodes', models.CharField(blank=True, max_length=150, null=True, verbose_name='Штрихкоды')),
                ('order_status', models.SmallIntegerField(choices=[(0, 'Создана'), (1, 'Ожидает приёмки'), (2, 'В доставке'), (3, 'Доставлена'), (4, 'Выдана'), (5, 'Просрочена'), (6, 'Забрана на возврат'), (7, 'На хранении'), (8, 'На возврате'), (9, 'Возвращена'), (10, 'Проблемная'), (11, 'Техническая проблема'), (12, 'Отменена'), (13, 'Хранение продлено клиентом'), (14, 'Объявлена'), (15, 'Хранится'), (16, 'Готово к получению'), (17, 'Получено'), (18, 'Готово к изъятию'), (19, 'Изъято')], default=0, verbose_name='Статус отправления')),
                ('msg_status', models.SmallIntegerField(choices=[(0, 'Новое'), (1, 'Отправлено'), (2, 'Запланировано'), (3, 'Не отправлено'), (4, 'Техническая проблема')], default=0, verbose_name='Статус сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='MessageStatistic',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('sent', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Отправленно')),
                ('unsent', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Не отправленно')),
                ('problem', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Проблемных')),
                ('new', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Новых')),
                ('planned', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Запланированных')),
            ],
            options={
                'verbose_name': 'Статистика',
            },
        ),
        migrations.DeleteModel(
            name='Message_Statistics',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
    ]
