# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190226_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_backout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время забора на возврат'),
        ),
        migrations.AddField(
            model_name='report',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закладки'),
        ),
        migrations.AddField(
            model_name='report',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время получения'),
        ),
        migrations.AddField(
            model_name='report',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения срока хранения'),
        ),
        migrations.AddField(
            model_name='report',
            name='size',
            field=models.SmallIntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'S/2'), (6, 'M/2')], default=1, verbose_name='Типоразмер'),
        ),
    ]
